package com.demo.events.dto;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.time.Instant;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Verifies that all event DTOs serialize/deserialize correctly through Jackson.
 * Records are deserialized via their canonical constructor; the sealed hierarchy
 * means the compiler enforces exhaustiveness in switch expressions.
 */
class EventDtoSerializationTest {

    ObjectMapper mapper;

    @BeforeEach
    void setUp() {
        mapper = new ObjectMapper();
        mapper.findAndRegisterModules(); // picks up JavaTimeModule for Instant
    }

    // ── Individual DTO tests ──────────────────────────────────────────────────

    @Test
    void userRegisteredEvent_roundTrips() throws Exception {
        UserRegisteredEvent original = UserRegisteredEvent.of("user_1", "test@example.com", "email");
        String json        = mapper.writeValueAsString(original);
        BaseEvent restored = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(UserRegisteredEvent.class, restored);
        UserRegisteredEvent typed = (UserRegisteredEvent) restored;
        assertEquals("user_1",           typed.userId());
        assertEquals("test@example.com", typed.email());
        assertEquals("email",            typed.channel());
        assertNotNull(typed.eventId());
        assertNotNull(typed.occurredAt());
    }

    @Test
    void emailDeliveredEvent_roundTrips() throws Exception {
        EmailDeliveredEvent ev  = EmailDeliveredEvent.of("user_2", "msg_123");
        String json             = mapper.writeValueAsString(ev);
        BaseEvent restored      = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(EmailDeliveredEvent.class, restored);
        assertEquals("msg_123", ((EmailDeliveredEvent) restored).messageId());
    }

    @Test
    void emailFailedEvent_roundTrips() throws Exception {
        EmailFailedEvent ev = EmailFailedEvent.of("user_3", "msg_456", "bounce");
        String json         = mapper.writeValueAsString(ev);
        BaseEvent restored  = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(EmailFailedEvent.class, restored);
        EmailFailedEvent typed = (EmailFailedEvent) restored;
        assertEquals("msg_456", typed.messageId());
        assertEquals("bounce",  typed.reason());
    }

    @Test
    void linkClickedEvent_roundTrips() throws Exception {
        LinkClickedEvent ev = LinkClickedEvent.of("user_4", "msg_789", "https://example.com/promo");
        String json         = mapper.writeValueAsString(ev);
        BaseEvent restored  = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(LinkClickedEvent.class, restored);
        assertEquals("https://example.com/promo", ((LinkClickedEvent) restored).url());
    }

    @Test
    void pushDeliveredEvent_roundTrips() throws Exception {
        PushDeliveredEvent ev = PushDeliveredEvent.of("user_5", "notif_001");
        String json           = mapper.writeValueAsString(ev);
        BaseEvent restored    = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(PushDeliveredEvent.class, restored);
        assertEquals("notif_001", ((PushDeliveredEvent) restored).notificationId());
    }

    @Test
    void purchaseCompletedEvent_roundTrips() throws Exception {
        PurchaseCompletedEvent ev = PurchaseCompletedEvent.of("user_6", "ord_001", 99.99);
        String json               = mapper.writeValueAsString(ev);
        BaseEvent restored        = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(PurchaseCompletedEvent.class, restored);
        PurchaseCompletedEvent typed = (PurchaseCompletedEvent) restored;
        assertEquals("ord_001", typed.orderId());
        assertEquals(99.99,     typed.amount(), 0.001);
    }

    @Test
    void userUnsubscribedEvent_roundTrips() throws Exception {
        UserUnsubscribedEvent ev = UserUnsubscribedEvent.of("user_7", "email");
        String json              = mapper.writeValueAsString(ev);
        BaseEvent restored       = mapper.readValue(json, BaseEvent.class);

        assertInstanceOf(UserUnsubscribedEvent.class, restored);
        assertEquals("email", ((UserUnsubscribedEvent) restored).channel());
    }

    // ── Shared contract tests ────────────────────────────────────────────────

    @Test
    void baseEvent_hasEventIdAndOccurredAt() {
        UserRegisteredEvent ev = UserRegisteredEvent.of("u", "e@e.com", "email");
        assertNotNull(ev.eventId(),    "eventId must be auto-generated by factory");
        assertNotNull(ev.occurredAt(), "occurredAt must be auto-set by factory");
        assertFalse(ev.eventId().isBlank());
    }

    @Test
    void twoEvents_haveUniqueEventIds() {
        EmailDeliveredEvent e1 = EmailDeliveredEvent.of("u", "m1");
        EmailDeliveredEvent e2 = EmailDeliveredEvent.of("u", "m2");
        assertNotEquals(e1.eventId(), e2.eventId());
    }

    @Test
    void eventTypeDiscriminator_isPresentInJson() throws Exception {
        EmailOpenedEvent ev = EmailOpenedEvent.of("user_1", "msg_1");
        String json = mapper.writeValueAsString(ev);
        assertTrue(json.contains("\"eventType\""),
                "JSON must contain eventType discriminator field, got: " + json);
        assertTrue(json.contains("EMAIL_OPENED"),
                "JSON must contain the event type value, got: " + json);
    }

    @Test
    void canonicalConstructor_allowsDeserialization() throws Exception {
        // Simulate what Kafka's StringDeserializer hands to the consumer
        String raw = """
                {"eventType":"EMAIL_DELIVERED","eventId":"abc","userId":"u1",
                 "occurredAt":"2024-01-01T12:00:00Z","messageId":"m1"}
                """;
        BaseEvent ev = mapper.readValue(raw, BaseEvent.class);
        assertInstanceOf(EmailDeliveredEvent.class, ev);
        assertEquals("u1", ev.userId());
        assertEquals("abc", ev.eventId());
    }

    // ── Parameterized: all event variants ───────────────────────────────────

    static Stream<BaseEvent> allEventInstances() {
        return Stream.of(
            UserRegisteredEvent.of("u", "e@e.com", "email"),
            EmailSentEvent.of("u", "m1", "t1"),
            EmailDeliveredEvent.of("u", "m1"),
            EmailFailedEvent.of("u", "m1", "bounce"),
            EmailOpenedEvent.of("u", "m1"),
            LinkClickedEvent.of("u", "m1", "https://x.com"),
            PushSentEvent.of("u", "n1"),
            PushDeliveredEvent.of("u", "n1"),
            PushFailedEvent.of("u", "n1", "token_expired"),
            SmsDeliveredEvent.of("u", "s1"),
            SmsFailedEvent.of("u", "s1", "invalid_number"),
            UserUnsubscribedEvent.of("u", "email"),
            PurchaseCompletedEvent.of("u", "o1", 42.0)
        );
    }

    @ParameterizedTest
    @MethodSource("allEventInstances")
    void allEvents_serializeAndDeserializeWithoutLoss(BaseEvent original) throws Exception {
        String json    = mapper.writeValueAsString(original);
        BaseEvent back = mapper.readValue(json, BaseEvent.class);

        assertEquals(original.getClass(), back.getClass(),
                "Deserialized type must match original for " + original.getClass().getSimpleName());
        assertEquals(original.userId(),    back.userId());
        assertEquals(original.eventId(),   back.eventId());
    }

    @ParameterizedTest
    @MethodSource("allEventInstances")
    void allEvents_haveNonNullEventId(BaseEvent ev) {
        assertNotNull(ev.eventId());
        assertFalse(ev.eventId().isBlank());
    }

    @ParameterizedTest
    @MethodSource("allEventInstances")
    void allEvents_haveNonNullOccurredAt(BaseEvent ev) {
        assertNotNull(ev.occurredAt());
        assertTrue(ev.occurredAt().isAfter(Instant.now().minusSeconds(60)));
    }

    @Test
    void sealedHierarchy_exhaustiveSwitch() {
        // Compiler enforces this is exhaustive — if a new type is added to the
        // sealed interface without a case here, this will fail to compile.
        BaseEvent ev = EmailDeliveredEvent.of("u", "m1");
        String channel = switch (ev) {
            case UserRegisteredEvent    e -> "user";
            case EmailSentEvent        e -> "email";
            case EmailDeliveredEvent   e -> "email";
            case EmailFailedEvent      e -> "email";
            case EmailOpenedEvent      e -> "email";
            case LinkClickedEvent      e -> "email";
            case PushSentEvent         e -> "push";
            case PushDeliveredEvent    e -> "push";
            case PushFailedEvent       e -> "push";
            case SmsDeliveredEvent     e -> "sms";
            case SmsFailedEvent        e -> "sms";
            case UserUnsubscribedEvent e -> "user";
            case PurchaseCompletedEvent e -> "commerce";
        };
        assertEquals("email", channel);
    }
}
